apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW5h
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4xMjM=


